[package]
name = "knn"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
default = []
rayon = ["ndarray/rayon"]

[dependencies]
mnist = { path = "../mnist" }
ndarray = { workspace = true }
ndarray-stats = { workspace = true }
