name: Github Pages Deploy
on:
  push:
    branches:
    - main

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM
        env:
          TARGET: ./target/wasm
          SRC: ./wasm
        run: |
          # build wasm
          wasm-pack build --target web --release --scope wasm -d $TARGET/mnist-rs $SRC/mnist-rs
          wasm-pack build --target web --release --scope wasm -d $TARGET/unpack $SRC/unpack
          # remove .gitignore
          rm $(find $TARGET -name .gitignore)

      - name: Build site
        env:
          WEB: ./web
          DIST: ../dist
        run: |
          npm install
          npx vite build $WEB --outDir $DIST --emptyOutDir --base=/${{ github.event.repository.name }}/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: ./dist # The folder the action should deploy.

