name: Github Pages site
on:
  push:
    branches:
    - main

jobs:
  deploy:
    concurrency: ci-${{ github.ref }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
          cache: 'npm'
          cache-dependency-path: web/package-lock.json
      
      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM
        run: |
          cd wasm
          wasm-pack build --target web --release --scope wasm -d ../target/wasm/kmeans ./kmeans
          wasm-pack build --target web --release --scope wasm -d ../target/wasm/mnist ./mnist
          wasm-pack build --target web --release --scope wasm -d ../target/wasm/wams-tar ./wasm-tar  
          rm $(find ./target/wasm -name .gitignore)

      - name: Build site
        run: |
          cd web
          npm install
          npm run build -- --base=/${{ github.event.repository.name }}/

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          branch: gh-pages # The branch the action should deploy to.
          folder: web/dist # The folder the action should deploy.

