name: Blazing fast GitHub Pages deploy

on:
  push:
    branches:
    - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@main

      - name: Install wasm-pack
        run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh

      - name: Build WASM
        run: |
          wasm-pack build -d web/pkg --target web --release
          rm web/pkg/.gitignore

      - name: Build site
        run: |
          cd web
          npm ci --only=production
          npm run build

      - name: Deploy site to gh-pages branch
        uses: alex-page/blazing-fast-gh-pages-deploy@v1.1.0
        with:
          repo-token: ${{ secrets.GH_PAT }}
          site-directory: web/dist
          deploy-branch: gh-pages
