name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:    
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose

  build-gh-pages:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install wasm-pack
      run: curl https://rustwasm.github.io/wasm-pack/installer/init.sh -sSf | sh
    - name: test
      run: |
        cd web
        ls -al
    - name: Build gh-pages
      run: |      
        mkdir -p www
        wasm-pack build -d www/pkg --target web
        rm www/pkg/.gitignore
        cp web/* www
    - name: Push gh-pages
      run: |
        git config --global user.name "github-actions[bot]"
        git config --global user.email "jason.chengyao.wang@gmail.com"
        cd www; git add --all; git commit -m "deploy to gh-pages"; git push origin gh-pages;